# Generated by Django 4.2.3 on 2023-08-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('phone', models.PositiveIntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('doctor_Name', models.CharField(choices=[('dr.Lekha(Dermatologists)', 'dr.Lekha(Dermatologists)'), ('dr.DD.Kuruvilla(Emergency Medicine specialists)', 'dr.DD.Kuruvilla(Emergency Medicine specialists)'), ('dr.Anu(Allergists/immunologists)', 'dr.Anu(Allergists/immunologists)'), ('dr.Vipin(Colon and Rectal Surgeons)', 'dr.Vipin(Colon and Rectal Surgeons)'), ('dr.Emy(ENT Specialist)', 'dr.Emy(ENT Specialist)'), ('dr.Athira(Gynecologist)', 'dr.Athira(Gynecologist)'), ('dr.Akhil(Radiologist)', 'dr.Akhil(Radiologist)'), ('dr.Vyshak(Oncologist)', 'dr.Vyshak(Oncologist)'), ('dr.Rekha(Orthopedic Surgeon)', 'dr.Rekha(Orthopedic Surgeon)'), ('dr.Abi(Veterinarian)', 'dr.Abi(Veterinarian)')], max_length=200, null=True)),
                ('department', models.CharField(choices=[('Dermatologists', 'Dermatologists'), ('Emergency Medicine specialists', 'Emergency Medicine specialists'), ('Allergists/immunologists', 'Allergists/immunologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Gynecologist', 'Gynecologist'), ('Radiologist', 'Radiologist'), ('ENT Specialist', 'ENT Specialist'), ('Oncologist', 'Oncologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Veterinarian', 'Veterinarian')], max_length=50, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(max_length=300, null=True)),
                ('time_slot', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_Name_add', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctros')),
                ('department', models.CharField(choices=[('Dermatologists', 'Dermatologists'), ('Emergency Medicine specialists', 'Emergency Medicine specialists'), ('Allergists/immunologists', 'Allergists/immunologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Gynecologist', 'Gynecologist'), ('Radiologist', 'Radiologist'), ('ENT Specialist', 'ENT Specialist'), ('Oncologist', 'Oncologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Veterinarian', 'Veterinarian')], max_length=50)),
                ('qlification', models.CharField(max_length=99)),
            ],
        ),
    ]
