# Generated by Django 4.2.3 on 2023-08-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
