# Generated by Django 4.2.3 on 2023-08-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_appointment_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='appointment',
            name='dep',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Dermatologists', 'Dermatologists'), ('Emergency Medicine specialists', 'Emergency Medicine specialists'), ('Allergists/immunologists', 'Allergists/immunologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Gynecologist', 'Gynecologist'), ('Radiologist', 'Radiologist'), ('ENT Specialist', 'ENT Specialist'), ('Oncologist', 'Oncologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Veterinarian', 'Veterinarian')], max_length=50, null=True),
        ),
    ]
