# Generated by Django 4.2.3 on 2023-08-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_department_appointment_dep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dep',
        ),
    ]
