# Generated by Django 4.2.3 on 2023-08-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_appointment_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_Name',
            field=models.CharField(choices=[('dr.Venu(Cardiologist)', 'dr.Venu(Cardiologist)'), ('dr.Lekha(Dermatologists)', 'dr.Lekha(Dermatologists)'), ('dr.DD.Kuruvilla(Emergency Medicine specialists)', 'dr.DD.Kuruvilla(Emergency Medicine specialists)'), ('dr.Anu(Allergists/immunologists)', 'dr.Anu(Allergists/immunologists)'), ('dr.Vipin(Colon and Rectal Surgeons)', 'dr.Vipin(Colon and Rectal Surgeons)'), ('dr.Emy(ENT Specialist)', 'dr.Emy(ENT Specialist)'), ('dr.Athira(Gynecologist)', 'dr.Athira(Gynecologist)'), ('dr.Akhil(Radiologist)', 'dr.Akhil(Radiologist)'), ('dr.Vyshak(Oncologist)', 'dr.Vyshak(Oncologist)'), ('dr.Rekha(Orthopedic Surgeon)', 'dr.Rekha(Orthopedic Surgeon)'), ('dr.Abi(Veterinarian)', 'dr.Abi(Veterinarian)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qlification',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
